server:
  port: 10035

spring:
  application:
    name: user_api
  profiles:
    active: local
  datasource:
    username: sa
    password: ''
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS USER_DB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: USER_DB
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.netflix: ERROR
    org.springframework.ws.client.MessageTracing: TRACE
    org.springframework.ws.server.MessageTracing: TRACE
    org.springframework.aop.interceptor.CustomizableTraceInterceptor: TRACE